import type { ToolPackage } from '@gtm/mcp-runtime/types';
import { kbArticlesPackage } from './kb_articles/mcp-tools';

// Support-domain tool packages: in-worker knowledge base (no backend service).
// Index data is generated by bin/build-kb-index.mjs from customer_success/kb/
// in the gtm.ai monorepo; run it after editing KB articles.
export const supportPackages: ToolPackage[] = [kbArticlesPackage];
