import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import type { ToolDefinition, ToolPackage } from '@gtm/mcp-runtime/types';
import { linkedinPackages } from '@gtm/mcp-linkedin';
import { idPackages } from '@gtm/mcp-id';
import { orchestrationPackages } from '@gtm/mcp-orchestration';

// Contract parity gates: the Zod contract must not promise more than the PHP
// contract delivers. The oracle is generated by `php artisan gtm:contract-oracle`
// and committed at fixtures/contract-oracle/*.contract.json (see the README
// there for regeneration). Nine gates: five over the RESPONSE half of the
// contract and the route flags, then four over the REQUEST half.
//
//  1. FILTER PARITY. Every key a Zod filter declares must exist on the PHP
//     {Entity}Filter field list. This is the expensive one: a filter key the
//     PHP Filter class does not declare throws WrongFillableFromArrayFieldException
//     inside the backend, which surfaces to the caller as a 500, NOT as a 422.
//     An agent cannot recover from that, so the key must never leave our side.
//  2. ITEM PARITY. The Zod item projection must be a subset of the
//     {Entity}Domain field list: a key Zod invents is a field no envelope will
//     ever carry. Domain fields the projection omits are only a coverage gap,
//     so they are printed as a WARNING and do not fail.
//  3. MASS-ACTION PARITY, in BOTH directions. TS -> backend: massAction /
//     scheduleRequired on an action tool must equal the mass_action /
//     schedule_required the backend route reports, and the route must exist at
//     all. backend -> TS: every public mass_action route must be covered by a
//     tool that declares the flag, or be named in mass-action-allowlist.json.
//  4. STEP-ELIGIBILITY PARITY, the same shape for the OTHER bulk flag of §R4.
//     massAction and stepEligible are independent (a fan-out verb can have no
//     executor arm; a single-target verb can still be a plan step), so one gate
//     cannot stand in for the other. TS -> backend: stepEligible must equal the
//     route's step_eligible. backend -> TS: every public step_eligible route must
//     be covered by a tool that declares it, or be named in
//     step-eligible-allowlist.json. Gate 3 owns scheduleRequired for both, since
//     pacing is one flag riding on whichever bulk fact the verb has.
//  5. BULK-FLAG DECLARATION. Gates 3 and 4 compare RESOLVED booleans, and a
//     resolved `false` is ambiguous: `massAction` defaults to false in the PHP
//     constructor, so a verb whose author never asked the question is byte-identical
//     to one whose author answered "single-target". Both sides then agree, and the
//     gate passes on an unanswered question. `declared_arguments` (from
//     ReflectionAttribute::getArguments(), which returns only what the call site
//     passed) makes the difference visible, and this gate fails any ACTION route
//     that omits massAction. It reads the fixtures ALONE, so it covers all four
//     services including email, which has no MCP package to compare against.
//
// Gates 6-9 read the `rules` block the oracle dumps per route (the action's
// FormRequest rules(), flattened to one entry per rule key). They exist because
// the request body had no oracle at all until that block landed: nothing could
// tell a tool that sends {status} from one that sends {state}, which is how
// three GA tools shipped 422-ing on every possible call.
//
//  6. REQUIRED-FIELD PARITY. Every field the backend marks `required` has a slot
//     in the tool's inputSchema. `z.object` strips unknown keys before dispatch,
//     so a required field with no slot cannot be supplied by any agent under any
//     prompt: the tool 422s on every call for the life of the deployment.
//  7. UNKNOWN-KEY PARITY. No inputSchema key is outside the rule set, reported at
//     the shallowest undeclared path. Remaining drift is recorded per key with a
//     reason in request-parity-baseline.json, which may only shrink.
//  8. BOUND PARITY. No stated Zod bound is WIDER than the stated backend bound.
//     A schema promising page_size 0..500 against a max:200 route hands the agent
//     a 422 it could not predict. A bound the schema omits is the weaker case (the
//     backend answers a recoverable 422 naming the field), so it is a WARNING.
//  9. ENUM PARITY. A field the backend closes with `in:` is a z.enum with the same
//     values. This is the one rule an agent cannot recover from by reading the
//     error: a 422 says the value is invalid, never which values are valid. A
//     value the tool offers and the backend rejects fails; a value the backend
//     allows and the tool omits is a coverage WARNING.
//
// The gates never assert a bare boolean: every failure names the entity, the
// tool and the offending keys, so the drift is fixable from the message alone.
// Nothing is skipped silently either: every skip is printed with its reason, so
// a gate cannot go quiet by failing to resolve what it was meant to check.

type OracleField = { name: string; type: string; nullable: boolean; has_default: boolean };
type OracleEntity = {
  domain: { class: string; fields: OracleField[] };
  response: { class: string; fields: OracleField[] } | null;
  filter: { class: string; fields: string[] } | null;
};
type OracleRoute = {
  method: string;
  uri: string;
  operation: string | null;
  mass_action: boolean;
  step_eligible: boolean;
  schedule_required: boolean;
  /** The #[ApiMethod] arguments the PHP call site actually wrote (gate 5). */
  declared_arguments?: string[];
  internal: boolean;
  /** FormRequest on the action's signature; null when it takes none (gates 6-9). */
  request_class?: string | null;
  /** The action's rules(), one entry per rule key; null when unreadable (gates 6-9). */
  rules?: OracleRule[] | null;
  /** Why `rules` is null; null when it is not. */
  rules_reason?: string | null;
};
type OracleRule = {
  /** The rule key verbatim, dots and wildcards included ('plan.steps.*.tool'). */
  field: string;
  rules: string[];
  required: boolean;
  nullable: boolean;
  type: string | null;
  /** Literal values, enum-backed ones already resolved; null when unrestricted. */
  in: Array<string | number> | null;
  min: number | string | null;
  max: number | string | null;
  size: number | string | null;
  between: Array<number | string> | null;
};
type Oracle = { service: string; entities: Record<string, OracleEntity>; routes: OracleRoute[] };
type AllowlistEntry = { route: string; reason: string };
type BaselineEntry = { tool: string; path: string; reason: string };
type RequestBaseline = { unknown_keys: Record<string, BaselineEntry[]> };

const ALLOWLIST_FILE = 'fixtures/contract-oracle/mass-action-allowlist.json';
const STEP_ALLOWLIST_FILE = 'fixtures/contract-oracle/step-eligible-allowlist.json';
const REQUEST_BASELINE_FILE = 'fixtures/contract-oracle/request-parity-baseline.json';

const readJson = (path: string) =>
  JSON.parse(readFileSync(new URL(path, import.meta.url), 'utf8'));

const load = (file: string): Oracle => readJson(`../fixtures/contract-oracle/${file}`);

const massActionAllowlist: Record<string, AllowlistEntry[]> = readJson(`../${ALLOWLIST_FILE}`);
const stepEligibleAllowlist: Record<string, AllowlistEntry[]> = readJson(`../${STEP_ALLOWLIST_FILE}`);
const requestBaseline: RequestBaseline = readJson(`../${REQUEST_BASELINE_FILE}`);

// A service with no MCP package is carried with an empty package set rather than
// left out. Gates 1 and 2 then check nothing for it (no Zod side to check), but
// the REVERSE direction of gates 3 and 4 is exactly what a package-less service
// needs: it reads the backend's own flags, so a mass-action or step-eligible verb
// with no tool has to be waived by name with a reason instead of passing because
// nobody listed the service. gtm.service.email is that case today.
const SERVICES: { name: 'linkedin' | 'id' | 'orchestration' | 'email'; packages: ToolPackage[]; oracle: Oracle }[] = [
  { name: 'linkedin', packages: linkedinPackages, oracle: load('linkedin.contract.json') },
  { name: 'id', packages: idPackages, oracle: load('id.contract.json') },
  { name: 'orchestration', packages: orchestrationPackages, oracle: load('orchestration.contract.json') },
  { name: 'email', packages: [], oracle: load('email.contract.json') },
];

// ─── Zod introspection ──────────────────────────────────────────────────
// Minimal walk over the Zod v3 `_def` tree. Only what the envelope builders in
// @gtm/mcp-shared actually produce is handled; anything else returns null and
// the caller counts the tool as skipped rather than guessing at its shape.

/* eslint-disable @typescript-eslint/no-explicit-any */
const unwrap = (schema: unknown): any => {
  let current: any = schema;
  for (let hops = 0; hops < 10 && current?._def; hops++) {
    switch (current._def.typeName) {
      case 'ZodOptional':
      case 'ZodNullable':
      case 'ZodDefault':
      case 'ZodReadonly':
        current = current._def.innerType;
        break;
      case 'ZodEffects':
        current = current._def.schema;
        break;
      case 'ZodLazy':
        current = current._def.getter();
        break;
      default:
        return current;
    }
  }
  return current;
};

const shapeOf = (schema: unknown): Record<string, unknown> | null => {
  const inner = unwrap(schema);
  return inner?._def?.typeName === 'ZodObject' ? (inner.shape as Record<string, unknown>) : null;
};

/** search envelope: { items: [{ item, included }] }; get envelope: { item }. */
const itemShapeOf = (tool: ToolDefinition): Record<string, unknown> | null => {
  const envelope = shapeOf(tool.outputSchema);
  if (!envelope) return null;
  if (tool.operation === 'get') return shapeOf(envelope.item);
  const rows = unwrap(envelope.items);
  if (rows?._def?.typeName !== 'ZodArray') return null;
  return shapeOf(shapeOf(rows._def.type)?.item);
};

// ─── request-side introspection (gates 6-9) ─────────────────────────────
// The gates above read the RESPONSE half of the contract. These read the
// REQUEST half, so they need the inputSchema flattened to the same dotted key
// space Laravel rule keys live in: an object key appends `.key`, an array
// element appends `.*`, and a union contributes every branch under the SAME
// path (`scope.kind` is one key whose value is four literals, not four keys).
// A record / unknown leaf stops the walk: its keys are data, not contract.

type ZodNode = { path: string; nodes: any[] };

const walk = (schema: unknown, prefix: string, into: Map<string, any[]>, depth = 0): void => {
  const node = unwrap(schema);
  const kind = node?._def?.typeName;
  if (prefix) into.set(prefix, [...(into.get(prefix) ?? []), node]);
  if (depth > 8) return;

  if (kind === 'ZodObject') {
    for (const [key, child] of Object.entries(node.shape as Record<string, unknown>)) {
      walk(child, prefix ? `${prefix}.${key}` : key, into, depth + 1);
    }
  } else if (kind === 'ZodArray') {
    walk(node._def.type, `${prefix}.*`, into, depth + 1);
  } else if (kind === 'ZodUnion') {
    for (const option of node._def.options) walk(option, prefix, into, depth + 1);
  }
};

const inputPathsOf = (tool: ToolDefinition): ZodNode[] => {
  const into = new Map<string, any[]>();
  walk(tool.inputSchema, '', into);
  return [...into.entries()].map(([path, nodes]) => ({ path, nodes }));
};

/** Declared value/length/count bounds, or null where the schema states none. */
const zodBounds = (node: any): { min: number | null; max: number | null } => {
  const kind = node?._def?.typeName;
  if (kind === 'ZodNumber' || kind === 'ZodString') {
    const checks: Array<{ kind: string; value: number }> = node._def.checks ?? [];
    const exact = checks.find((check) => check.kind === 'length')?.value ?? null;
    return {
      min: checks.find((check) => check.kind === 'min')?.value ?? exact,
      max: checks.find((check) => check.kind === 'max')?.value ?? exact,
    };
  }
  if (kind === 'ZodArray') {
    const exact = node._def.exactLength?.value ?? null;
    return { min: node._def.minLength?.value ?? exact, max: node._def.maxLength?.value ?? exact };
  }
  return { min: null, max: null };
};

/** The closed value set a node accepts, or null when it accepts an open one. */
const zodEnumValues = (node: any): string[] | null => {
  const kind = node?._def?.typeName;
  if (kind === 'ZodEnum') return [...node._def.values].map(String);
  if (kind === 'ZodNativeEnum') return Object.values(node._def.values).map(String);
  if (kind === 'ZodLiteral') return [String(node._def.value)];
  if (kind === 'ZodUnion') {
    const values: string[] = [];
    for (const option of node._def.options) {
      const branch = zodEnumValues(unwrap(option));
      if (!branch) return null;
      values.push(...branch);
    }
    return values;
  }
  return null;
};

const typeNameOf = (node: any): string => String(node?._def?.typeName ?? 'unknown').replace(/^Zod/, '');
/* eslint-enable @typescript-eslint/no-explicit-any */

// A rule key and a Zod path are compared segment by segment, because a rule key
// may carry `*` where the schema carries a concrete key: the backend writes
// `sync_config.entries.*.interval_minutes` once for the seven tracks the schema
// names individually, and a string compare would call all seven undeclared.
const segmentsOf = (path: string) => path.split('.');
const sameKey = (rule: string[], path: string[]) =>
  rule.length === path.length && rule.every((segment, i) => segment === '*' || segment === path[i]);
const ruleGoesDeeper = (rule: string[], path: string[]) =>
  rule.length > path.length && path.every((segment, i) => rule[i] === '*' || rule[i] === segment);

const numberOr = (value: number | string | null): number | null => (typeof value === 'number' ? value : null);

// ─── entity resolution ──────────────────────────────────────────────────
// ToolDefinition.entity is the snake_case plural route group ('api_keys');
// oracle keys are the PascalCase Domain class name minus the Domain suffix
// ('ApiKey'). The mapping is NOT one-to-one: one PHP entity FOLDER can hold
// several Domains, and one MCP package covers the whole folder. Id/Observability
// holds ObservabilityRequestDomain + ObservabilityAgentSessionDomain, and the
// single `observability_requests` package has a tool for each. Resolving the
// tool's entity to one Domain by name therefore checks half the tools against
// the wrong Domain and invents drift that is not there.
//
// So: resolve the entity to the CANDIDATE SET of every Domain in its folder,
// then attribute each TOOL to one candidate by fit (fewest keys the PHP side
// does not declare, then most keys it does, then name-token overlap). A tie is
// a genuine ambiguity: it is counted as a skip and printed, never guessed at.

const flatten = (value: string) => value.toLowerCase().replace(/[^a-z0-9]/g, '');
const singularize = (value: string) =>
  value.endsWith('ies') ? `${value.slice(0, -3)}y`
    : value.endsWith('sses') ? value.slice(0, -2)
      : value.endsWith('s') && !value.endsWith('ss') ? value.slice(0, -1)
        : value;

/** 'Gtm\Lib\Common\Microservices\Id\Observability\ObservabilityRequestDomain' -> 'Observability'. */
const folderOf = (domainClass: string) => domainClass.split('\\').slice(-2, -1)[0] ?? '';

const words = (value: string) =>
  value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((word) => singularize(word.toLowerCase()));

/** Shared word count between a tool name and an entity key, both singularized. */
const nameScore = (toolName: string, entityKey: string) => {
  const fromTool = new Set(words(toolName));
  return words(entityKey).filter((word) => fromTool.has(word)).length;
};

type Fit = { key: string; extra: string[]; hits: number; name: number };

/** Best fit first: fewest undeclared keys, then most declared, then name overlap. */
const byFit = (a: Fit, b: Fit) => a.extra.length - b.extra.length || b.hits - a.hits || b.name - a.name;

const fitOf = (key: string, zodKeys: string[], phpFields: string[], toolName: string): Fit => ({
  key,
  extra: zodKeys.filter((zodKey) => !phpFields.includes(zodKey)),
  hits: zodKeys.filter((zodKey) => phpFields.includes(zodKey)).length,
  name: nameScore(toolName, key),
});

const routeKey = (tool: ToolDefinition) =>
  `${tool.route.method} ${tool.route.pathTemplate.replace(/^\//, '')}`;

for (const svc of SERVICES) {
  describe(`contract parity gate: ${svc.name}`, () => {
    const tools = svc.packages.flatMap((p) => p.tools);

    const byFlatName = new Map<string, string>();
    const byFlatFolder = new Map<string, string>();
    const keysByFolder = new Map<string, string[]>();
    for (const [key, entity] of Object.entries(svc.oracle.entities)) {
      const folder = folderOf(entity.domain.class);
      byFlatName.set(flatten(key), key);
      byFlatFolder.set(flatten(folder), folder);
      keysByFolder.set(folder, [...(keysByFolder.get(folder) ?? []), key]);
    }

    /** Every oracle entity the tool's entity folder holds (usually exactly one). */
    const candidatesFor = (entity: string): string[] => {
      const flat = flatten(entity);
      const named = byFlatName.get(flat) ?? byFlatName.get(singularize(flat));
      const folder = named
        ? folderOf(svc.oracle.entities[named].domain.class)
        : byFlatFolder.get(flat) ?? byFlatFolder.get(singularize(flat));
      if (!folder) return [];
      return keysByFolder.get(folder) ?? (named ? [named] : []);
    };

    /** Picks the one candidate the tool fits, or null when two fit equally. */
    const attribute = (fits: Fit[]): { pick: Fit | null; tied: string[] } => {
      const ranked = [...fits].sort(byFit);
      const [best, runnerUp] = ranked;
      if (!best) return { pick: null, tied: [] };
      if (runnerUp && byFit(best, runnerUp) === 0) {
        return { pick: null, tied: ranked.filter((fit) => byFit(best, fit) === 0).map((fit) => fit.key) };
      }
      return { pick: best, tied: [] };
    };

    const report = (label: string, checked: number, skipped: string[]) => {
      /* eslint-disable no-console */
      console.log(`${svc.name} ${label}: ${checked} tools checked, ${skipped.length} skipped.`);
      for (const line of skipped) console.log(`  skipped: ${line}`);
      /* eslint-enable no-console */
    };

    // Both bulk-flag gates below walk the same two indexes.
    const byRouteKey = new Map<string, OracleRoute>();
    for (const route of svc.oracle.routes) byRouteKey.set(`${route.method} ${route.uri}`, route);

    const toolsByRouteKey = new Map<string, ToolDefinition[]>();
    for (const tool of tools) {
      const key = routeKey(tool);
      toolsByRouteKey.set(key, [...(toolsByRouteKey.get(key) ?? []), tool]);
    }

    /**
     * backend -> TS for one bulk flag. A route the backend marks and no tool
     * declares is the direction that can be missed in silence, so it fails unless
     * the allow-list names it with a reason; an allow-list entry that stopped
     * applying fails too, which is what keeps the list shrinking.
     */
    const reverseDirection = (
      allowlistFile: string,
      entries: AllowlistEntry[],
      flagOf: (route: OracleRoute) => boolean,
      flagName: string,
      violations: string[],
    ): string[] => {
      const allowlist = new Map(entries.map((entry) => [entry.route, entry.reason]));
      const waived: string[] = [];

      for (const route of svc.oracle.routes) {
        if (!flagOf(route) || !route.uri.startsWith('api/') || route.internal) continue;

        const key = `${route.method} ${route.uri}`;
        if ((toolsByRouteKey.get(key) ?? []).length) continue;

        const reason = allowlist.get(key);
        if (reason === undefined) {
          violations.push(`${key}: the backend reports ${flagName}, no MCP tool covers it, and it is not in ${allowlistFile}`);
        } else {
          waived.push(`${key} (${reason})`);
        }
      }

      // An allow-list entry that stopped applying is debt we have already paid
      // and must stop carrying, so it fails exactly like unrecorded drift.
      for (const [key, reason] of allowlist) {
        const route = byRouteKey.get(key);
        const covering = toolsByRouteKey.get(key) ?? [];
        if (!route) {
          violations.push(`${allowlistFile} lists ${key}: the backend serves no such route any more, delete the line (was: ${reason})`);
        } else if (!flagOf(route)) {
          violations.push(`${allowlistFile} lists ${key}: the backend no longer reports ${flagName}, delete the line (was: ${reason})`);
        } else if (covering.length) {
          violations.push(`${allowlistFile} lists ${key}: ${covering.map((tool) => tool.name).join(', ')} covers it now, delete the line (was: ${reason})`);
        }
      }

      return waived;
    };

    // One-time secrets (create/rotate only) live on the shared item projection
    // but are deliberately absent from the Domain, exactly like ApiKeyDomain's
    // token_hash. The registry already declares them per tool, so the item gate
    // reads that declaration instead of carrying a hand-written allowlist.
    const secretFieldsByEntity = new Map<string, Set<string>>();
    for (const tool of tools) {
      for (const field of tool.allowSecretFields ?? []) {
        const bucket = secretFieldsByEntity.get(tool.entity) ?? new Set<string>();
        bucket.add(field);
        secretFieldsByEntity.set(tool.entity, bucket);
      }
    }

    it('filter parity: every Zod filter key exists on the PHP {Entity}Filter', () => {
      const violations: string[] = [];
      const skipped: string[] = [];
      const attributed: string[] = [];
      let checked = 0;

      for (const tool of tools) {
        const input = shapeOf(tool.inputSchema);
        if (!input?.filter) continue;

        const filterShape = shapeOf(input.filter);
        if (!filterShape) {
          skipped.push(`${tool.name}: the filter input is not a plain object`);
          continue;
        }

        const keys = Object.keys(filterShape);
        const candidates = candidatesFor(tool.entity).filter((key) => svc.oracle.entities[key].filter);
        if (!candidates.length) {
          skipped.push(`${tool.name}: entity '${tool.entity}' has no {Entity}Filter in the oracle`);
          continue;
        }

        const { pick, tied } = attribute(
          candidates.map((key) => fitOf(key, keys, svc.oracle.entities[key].filter!.fields, tool.name)),
        );
        if (!pick) {
          skipped.push(`${tool.name}: entity '${tool.entity}' is ambiguous, ${tied.join(' / ')} fit its filter keys equally well`);
          continue;
        }
        if (candidates.length > 1) attributed.push(`${tool.name} -> ${pick.key}Filter (of ${candidates.join(', ')})`);

        checked++;
        if (pick.extra.length) {
          violations.push(
            `${tool.name} -> ${pick.key}Filter has no ${pick.extra.join(', ')} (500 on call, not 422)`,
          );
        }
      }

      report('filter parity', checked, skipped);
      /* eslint-disable-next-line no-console */
      for (const line of attributed) console.log(`  multi-domain folder, attributed by fit: ${line}`);
      expect(violations).toEqual([]);
    });

    it('item parity: the Zod item never invents a field the {Entity}Domain lacks', () => {
      const invented: string[] = [];
      const uncovered: string[] = [];
      const skipped: string[] = [];
      const attributed: string[] = [];
      let checked = 0;

      for (const tool of tools) {
        if (tool.operation !== 'search' && tool.operation !== 'get') continue;

        const itemShape = itemShapeOf(tool);
        if (!itemShape) {
          skipped.push(`${tool.name}: the item schema is not a plain object`);
          continue;
        }

        const candidates = candidatesFor(tool.entity);
        if (!candidates.length) {
          skipped.push(`${tool.name}: entity '${tool.entity}' is absent from the oracle`);
          continue;
        }

        // A secret the tool declares is not a Domain field and must not count
        // against the fit either, or it would drag every candidate down equally.
        const secrets = secretFieldsByEntity.get(tool.entity) ?? new Set<string>();
        const keys = Object.keys(itemShape).filter((key) => !secrets.has(key));

        const { pick, tied } = attribute(
          candidates.map((key) =>
            fitOf(key, keys, svc.oracle.entities[key].domain.fields.map((field) => field.name), tool.name)),
        );
        if (!pick) {
          skipped.push(`${tool.name}: entity '${tool.entity}' is ambiguous, ${tied.join(' / ')} fit its item projection equally well`);
          continue;
        }
        if (candidates.length > 1) attributed.push(`${tool.name} -> ${pick.key}Domain (of ${candidates.join(', ')})`);

        checked++;
        if (pick.extra.length) {
          invented.push(`${tool.name} -> ${pick.key}Domain has no ${pick.extra.join(', ')}`);
        }
        const missing = svc.oracle.entities[pick.key].domain.fields
          .map((field) => field.name)
          .filter((field) => !(field in itemShape));
        if (missing.length) {
          uncovered.push(`${tool.name} -> ${pick.key}Domain field(s) not projected: ${missing.join(', ')}`);
        }
      }

      report('item parity', checked, skipped);
      /* eslint-disable no-console */
      for (const line of attributed) console.log(`  multi-domain folder, attributed by fit: ${line}`);
      if (uncovered.length) {
        console.log(`${svc.name} item parity WARNING: ${uncovered.length} tool(s) omit Domain fields (coverage gap, not a failure):`);
        for (const line of uncovered) console.log(`  ${line}`);
      }
      /* eslint-enable no-console */
      expect(invented).toEqual([]);
    });

    it('mass-action parity: massAction / scheduleRequired match the backend route, both directions', () => {
      const violations: string[] = [];
      let checked = 0;

      const compare = (tool: ToolDefinition, key: string, route: OracleRoute) => {
        const massAction = tool.massAction ?? false;
        const scheduleRequired = tool.scheduleRequired ?? false;
        if (massAction !== route.mass_action) {
          violations.push(`${tool.name} -> ${key}: massAction is ${massAction}, backend mass_action is ${route.mass_action}`);
        }
        if (scheduleRequired !== route.schedule_required) {
          violations.push(`${tool.name} -> ${key}: scheduleRequired is ${scheduleRequired}, backend schedule_required is ${route.schedule_required}`);
        }
      };

      // ── TS -> backend. A tool aimed at a route the backend does not serve is
      // the bug class this whole file exists to close, so it FAILS here; it is
      // not a skip. (The coverage gate reports the same drift for every tool,
      // not just action verbs.)
      for (const tool of tools) {
        if (tool.operation !== 'action') continue;

        const key = routeKey(tool);
        const route = byRouteKey.get(key);
        if (!route) {
          violations.push(`${tool.name} -> ${key}: the backend serves no such route, so its mass-action flags are unverifiable (retire or repoint the tool)`);
          continue;
        }

        checked++;
        compare(tool, key, route);
      }

      // ── backend -> TS. A mass-action route fans one call out over
      // filter/targets[], so "the backend has it and we forgot the tool" is the
      // expensive direction to miss. Every public one is covered by a tool that
      // declares the flag, or named in the allow-list with a reason.
      const waived = reverseDirection(
        ALLOWLIST_FILE, massActionAllowlist[svc.name] ?? [],
        (route) => route.mass_action, 'mass_action', violations,
      );

      // Action verbs were compared above; anything else reaching a mass-action
      // route was never checked, and is itself suspect.
      for (const route of svc.oracle.routes) {
        if (!route.mass_action || !route.uri.startsWith('api/') || route.internal) continue;

        const key = `${route.method} ${route.uri}`;
        for (const tool of (toolsByRouteKey.get(key) ?? []).filter((candidate) => candidate.operation !== 'action')) {
          violations.push(`${tool.name} -> ${key}: the backend reports mass_action on this route but the tool's operation is '${tool.operation}', not 'action'`);
          compare(tool, key, route);
        }
      }

      /* eslint-disable no-console */
      console.log(`${svc.name} mass-action parity: ${checked} action tools checked against the oracle, ${waived.length} backend mass-action route(s) waived by ${ALLOWLIST_FILE}.`);
      for (const line of waived) console.log(`  waived: ${line}`);
      /* eslint-enable no-console */
      expect(violations).toEqual([]);
    });

    // The other half of the §R4 pair. It is a separate gate rather than two more
    // lines in the one above because the flags are independent: react_linkedin_post
    // is both, send_linkedin_connection_request is step-eligible only, and
    // account-shares.recall is mass-action only. A verb the engine can plan but we
    // expose no tool for is the failure this direction exists to catch: the run
    // spends its targets on a verb the agent can neither describe nor call.
    it('step-eligibility parity: stepEligible matches the backend route, both directions', () => {
      const violations: string[] = [];
      let checked = 0;

      // ── TS -> backend. Same rule as the mass-action gate: a tool pointed at a
      // route the backend does not serve fails here, it is not skipped.
      for (const tool of tools) {
        if (tool.operation !== 'action') continue;

        const key = routeKey(tool);
        const route = byRouteKey.get(key);
        if (!route) {
          violations.push(`${tool.name} -> ${key}: the backend serves no such route, so its stepEligible flag is unverifiable (retire or repoint the tool)`);
          continue;
        }

        checked++;
        const stepEligible = tool.stepEligible ?? false;
        if (stepEligible !== route.step_eligible) {
          violations.push(`${tool.name} -> ${key}: stepEligible is ${stepEligible}, backend step_eligible is ${route.step_eligible}`);
        }
      }

      // ── backend -> TS.
      const waived = reverseDirection(
        STEP_ALLOWLIST_FILE, stepEligibleAllowlist[svc.name] ?? [],
        (route) => route.step_eligible, 'step_eligible', violations,
      );

      // A non-action tool on a step-eligible route was never compared above, and
      // orchestration calling a verb we model as a read is a contradiction.
      for (const route of svc.oracle.routes) {
        if (!route.step_eligible || !route.uri.startsWith('api/') || route.internal) continue;

        const key = `${route.method} ${route.uri}`;
        for (const tool of (toolsByRouteKey.get(key) ?? []).filter((candidate) => candidate.operation !== 'action')) {
          violations.push(`${tool.name} -> ${key}: the backend reports step_eligible on this route but the tool's operation is '${tool.operation}', not 'action'`);
        }
      }

      /* eslint-disable no-console */
      console.log(`${svc.name} step-eligibility parity: ${checked} action tools checked against the oracle, ${waived.length} backend step-eligible route(s) waived by ${STEP_ALLOWLIST_FILE}.`);
      for (const line of waived) console.log(`  waived: ${line}`);
      /* eslint-enable no-console */
      expect(violations).toEqual([]);
    });

    // ─── gates 6-9: REQUEST parity ────────────────────────────────────────
    // Everything above compares what comes BACK. These four compare what goes
    // IN, against the `rules` block the oracle now dumps per route (the action's
    // FormRequest rules(), one entry per rule key). Until it existed the request
    // body had no oracle at all, which is how three GA tools shipped 422-ing on
    // every possible call: nothing could tell a tool that sends {status} from one
    // that sends {state} short of a tenant hitting the 422.
    //
    // Shared preamble for all four: resolve the tool to its route, then skip
    // (out loud) the routes that cannot answer.
    //   - `rules: null` - the dump could not read a rule set, `rules_reason` says
    //     why. Printed with the reason; NEVER a silent pass.
    //   - `rules: []` - a FormRequest that declares no rules, so the body is
    //     unconstrained and there is nothing to compare a schema against. A
    //     different statement from null, printed as its own skip.
    // Keys the runtime consumes before the request is built are excluded on the
    // Zod side, because the backend never sees them: `_meta` (usage analytics,
    // dropped in url.ts), the {sid} / pathParams bindings (they travel in the
    // path, not the body), and `commit_token` on dangerous tools (the preview
    // gate strips it).

    type RequestCase = { tool: ToolDefinition; route: OracleRoute; rules: OracleRule[]; paths: ZodNode[]; consumed: Set<string> };

    const skippedRequests: string[] = [];
    const requestCases: RequestCase[] = [];
    for (const tool of tools) {
      const key = routeKey(tool);
      const route = byRouteKey.get(key);
      if (!route) {
        skippedRequests.push(`${tool.name}: the backend serves no route ${key} (the coverage gate owns that drift)`);
        continue;
      }
      if (!Array.isArray(route.rules)) {
        skippedRequests.push(`${tool.name} -> ${key}: rules could not be dumped (${route.rules_reason ?? 'no reason recorded'})`);
        continue;
      }
      if (route.rules.length === 0) {
        skippedRequests.push(`${tool.name} -> ${key}: ${route.request_class ?? 'the FormRequest'} declares no rules, so nothing constrains the body`);
        continue;
      }

      const consumed = new Set<string>(['_meta']);
      if (tool.dangerous) consumed.add('commit_token');
      if (tool.route.pathTemplate.includes('{sid}')) consumed.add(tool.route.sidParam ?? 'sid');
      for (const bound of Object.values(tool.route.pathParams ?? {})) consumed.add(bound);

      requestCases.push({ tool, route, rules: route.rules, paths: inputPathsOf(tool), consumed });
    }

    const reportRequests = (label: string, extra = '') => {
      /* eslint-disable no-console */
      console.log(`${svc.name} ${label}: ${requestCases.length} tools checked against route rules, ${skippedRequests.length} skipped.${extra}`);
      for (const line of skippedRequests) console.log(`  skipped: ${line}`);
      /* eslint-enable no-console */
    };

    /** The rule whose key matches this Zod path exactly (wildcards included). */
    const ruleAt = (rules: OracleRule[], path: string[]) =>
      rules.find((rule) => sameKey(segmentsOf(rule.field), path)) ?? null;

    it('request parity: every field the backend REQUIRES has a slot in the inputSchema', () => {
      // The sharpest class in this file. `z.object` strips unknown keys before
      // dispatch, so a required field the schema has no slot for cannot be
      // supplied by any agent, by any wording of any prompt: the tool 422s on
      // every possible call for the whole life of the deployment, and the agent
      // reads back "the field is required" about a field it was never offered.
      const violations: string[] = [];

      for (const { tool, route, rules, paths, consumed } of requestCases) {
        for (const rule of rules) {
          if (!rule.required) continue;
          const segments = segmentsOf(rule.field);
          if (consumed.has(segments[0])) continue;
          if (paths.some((candidate) => sameKey(segments, segmentsOf(candidate.path)))) continue;

          violations.push(
            `${tool.name} -> ${route.method} ${route.uri}: the backend requires '${rule.field}' (${rule.rules.join('|')}) and the inputSchema has no slot for it, so every call 422s`,
          );
        }
      }

      reportRequests('required-field parity');
      expect(violations).toEqual([]);
    });

    it('request parity: no inputSchema key is unknown to the route rules', () => {
      // A key the rule set never mentions is a key outside the contract: it is
      // validated by nothing, and whether the controller happens to read it is
      // an implementation detail no gate can see. Reported at the SHALLOWEST
      // undeclared path - once `filter.updated_at` is named, its `.gte` / `.lte`
      // operator keys add nothing.
      //
      // A path counts as declared when a rule key matches it, when it is a
      // prefix of a deeper rule key (a container the backend addresses further
      // down), or when the nearest declared ancestor is a rule LEAF: `filter.q`
      // and `filter.status` are declared whole, so the operator object below
      // them is inside the contract. The nearest ancestor having rule children
      // is the opposite statement - the backend enumerated what may sit there,
      // and this key is not on the list.
      const violations: string[] = [];
      const waived: string[] = [];
      const baseline = new Map(
        (requestBaseline.unknown_keys[svc.name] ?? []).map((entry) => [`${entry.tool}:${entry.path}`, entry.reason]),
      );
      const seen = new Set<string>();

      for (const { tool, route, rules, paths, consumed } of requestCases) {
        const ruleKeys = rules.map((rule) => ({ rule, segments: segmentsOf(rule.field) }));
        const isContainer = (path: string[]) => ruleKeys.some((entry) => ruleGoesDeeper(entry.segments, path));
        const hasRuleChildren = (field: string) => {
          const own = segmentsOf(field);
          return ruleKeys.some(
            (entry) => entry.segments.length > own.length && own.every((segment, i) => segment === '*' || entry.segments[i] === segment),
          );
        };

        const flagged: string[] = [];
        for (const candidate of [...paths].sort((a, b) => segmentsOf(a.path).length - segmentsOf(b.path).length)) {
          const segments = segmentsOf(candidate.path);
          if (consumed.has(segments[0])) continue;
          if (flagged.some((parent) => candidate.path === parent || candidate.path.startsWith(`${parent}.`))) continue;
          if (ruleAt(rules, segments)) continue;
          if (isContainer(segments)) continue;

          let why = `no rule key covers it`;
          for (let cut = segments.length - 1; cut >= 1; cut--) {
            const ancestor = segments.slice(0, cut);
            const owner = ruleAt(rules, ancestor);
            if (owner) {
              if (!hasRuleChildren(owner.field)) { why = ''; break; }
              why = `'${owner.field}' enumerates its children and this is not one of them`;
              break;
            }
            if (isContainer(ancestor)) {
              why = `'${ancestor.join('.')}' is declared only through deeper rule keys and this is not one of them`;
              break;
            }
          }
          if (!why) continue;

          flagged.push(candidate.path);
          const key = `${tool.name}:${candidate.path}`;
          seen.add(key);
          const reason = baseline.get(key);
          if (reason === undefined) {
            violations.push(
              `${tool.name} -> ${route.method} ${route.uri}: the inputSchema declares '${candidate.path}' and ${route.request_class ?? 'the FormRequest'} does not (${why}); fix the tool, or record it in ${REQUEST_BASELINE_FILE} with a reason`,
            );
          } else {
            waived.push(`${key} (${reason})`);
          }
        }
      }

      // Same discipline as the two allow-lists: an entry that stopped drifting is
      // debt already paid, and carrying it is how a baseline stops shrinking.
      for (const [key, reason] of baseline) {
        if (!seen.has(key)) {
          violations.push(`${REQUEST_BASELINE_FILE} lists ${key} for ${svc.name}: it no longer drifts, delete the line (was: ${reason})`);
        }
      }

      reportRequests('unknown-key parity', ` ${waived.length} key(s) waived by ${REQUEST_BASELINE_FILE}.`);
      /* eslint-disable-next-line no-console */
      for (const line of waived) console.log(`  waived: ${line}`);
      expect(violations).toEqual([]);
    });

    it('request parity: no Zod bound is wider than the backend bound', () => {
      // A schema that promises MORE than the validator accepts is worse than one
      // that promises nothing: the agent reads `page_size: 0..500` off the tool
      // description, sends 500, and eats a 422 it had no way to predict. 23
      // search tools advertised exactly that against a max:200 backend.
      //
      // A bound the schema simply omits is a different, weaker thing - the tool
      // promises nothing, the backend answers with a recoverable 422 naming the
      // field - so it is printed as a warning and does not fail. Only a stated
      // bound wider than the stated backend bound fails here.
      const violations: string[] = [];
      const unbounded: string[] = [];

      for (const { tool, route, rules, paths, consumed } of requestCases) {
        for (const rule of rules) {
          const segments = segmentsOf(rule.field);
          if (consumed.has(segments[0])) continue;
          const candidate = paths.find((entry) => sameKey(segments, segmentsOf(entry.path)));
          if (!candidate) continue;

          const backendMin = numberOr(rule.size ?? rule.between?.[0] ?? rule.min);
          const backendMax = numberOr(rule.size ?? rule.between?.[1] ?? rule.max);
          const declared = candidate.nodes.map(zodBounds);
          const kinds = candidate.nodes.map(typeNameOf).join(' | ');

          // A union is only as tight as its loosest branch, so an undeclared
          // bound on any branch leaves the whole key unbounded.
          const zodMax = declared.every((bound) => bound.max !== null)
            ? Math.max(...declared.map((bound) => bound.max as number)) : null;
          const zodMin = declared.every((bound) => bound.min !== null)
            ? Math.min(...declared.map((bound) => bound.min as number)) : null;

          if (backendMax !== null) {
            if (zodMax === null) unbounded.push(`${tool.name}: '${rule.field}' has backend max ${backendMax}, the ${kinds} schema states none`);
            else if (zodMax > backendMax) {
              violations.push(`${tool.name} -> ${route.method} ${route.uri}: '${rule.field}' allows up to ${zodMax}, the backend caps it at ${backendMax} (${rule.rules.join('|')})`);
            }
          }
          if (backendMin !== null) {
            if (zodMin === null) unbounded.push(`${tool.name}: '${rule.field}' has backend min ${backendMin}, the ${kinds} schema states none`);
            else if (zodMin < backendMin) {
              violations.push(`${tool.name} -> ${route.method} ${route.uri}: '${rule.field}' allows down to ${zodMin}, the backend floors it at ${backendMin} (${rule.rules.join('|')})`);
            }
          }
        }
      }

      reportRequests('bound parity');
      /* eslint-disable no-console */
      if (unbounded.length) {
        console.log(`${svc.name} bound parity WARNING: ${unbounded.length} field(s) carry a backend bound the schema does not state (recoverable 422, not a failure):`);
        for (const line of unbounded) console.log(`  ${line}`);
      }
      /* eslint-enable no-console */
      expect(violations).toEqual([]);
    });

    it('request parity: a field the backend restricts with Rule::in is a matching z.enum', () => {
      // `in:` is the one rule an agent cannot recover from by reading the error:
      // a 422 says the value is invalid, never which values are valid. The tool
      // has to carry the set, so a closed backend field must be a closed Zod
      // field with the same values.
      //
      // Two directions, weighted by what each costs. A value the schema offers
      // and the backend rejects is a guaranteed 422 the agent was invited to
      // make, so it FAILS. A value the backend allows and the schema omits only
      // narrows the tool - it is a coverage gap, printed as a warning.
      const violations: string[] = [];
      const narrowed: string[] = [];

      for (const { tool, route, rules, paths, consumed } of requestCases) {
        for (const rule of rules) {
          if (!Array.isArray(rule.in)) continue;
          const segments = segmentsOf(rule.field);
          if (consumed.has(segments[0])) continue;
          const candidate = paths.find((entry) => sameKey(segments, segmentsOf(entry.path)));
          if (!candidate) continue;

          const allowed = rule.in.map(String);
          const offered = candidate.nodes.map(zodEnumValues);
          if (offered.some((values) => values === null)) {
            violations.push(
              `${tool.name} -> ${route.method} ${route.uri}: the backend restricts '${rule.field}' to ${allowed.length} value(s) (${allowed.join(', ')}) and the tool advertises a bare ${candidate.nodes.map(typeNameOf).join(' | ')}, so the agent has to guess`,
            );
            continue;
          }

          const values = [...new Set(offered.flat() as string[])];
          const rejected = values.filter((value) => !allowed.includes(value));
          const missing = allowed.filter((value) => !values.includes(value));
          if (rejected.length) {
            violations.push(
              `${tool.name} -> ${route.method} ${route.uri}: '${rule.field}' offers ${rejected.join(', ')}, which the backend's in: list rejects (allowed: ${allowed.join(', ')})`,
            );
          }
          if (missing.length) narrowed.push(`${tool.name}: '${rule.field}' omits ${missing.join(', ')} of the backend's in: list`);
        }
      }

      reportRequests('enum parity');
      /* eslint-disable no-console */
      if (narrowed.length) {
        console.log(`${svc.name} enum parity WARNING: ${narrowed.length} field(s) offer fewer values than the backend accepts (coverage gap, not a failure):`);
        for (const line of narrowed) console.log(`  ${line}`);
      }
      /* eslint-enable no-console */
      expect(violations).toEqual([]);
    });
  });
}

// ─── gate 5: bulk-flag declaration ──────────────────────────────────────
// The one gate above that needs no TypeScript side at all: it compares the PHP
// contract against §R4 itself, so it reads the fixtures alone and therefore
// covers every service bin/oracle-refresh.sh dumps, whether or not it has an MCP
// package. It stays a separate loop from SERVICES because it needs no packages
// at all, not because the service list is short of anything.
//
// What it catches that gates 3 and 4 cannot: an ACTION verb that never wrote
// `massAction:` at all. Those gates compare resolved booleans, and the PHP
// constructor defaults massAction to false, so an unanswered question and a
// considered "single-target" produce the same false on both sides and agree
// perfectly. `declared_arguments` carries what the call site actually wrote
// (ReflectionAttribute::getArguments() returns only the passed arguments), which
// is the only place that difference survives.

const ORACLE_SERVICES = ['linkedin', 'id', 'orchestration', 'email'] as const;

describe('bulk-flag declaration gate', () => {
  for (const service of ORACLE_SERVICES) {
    const oracle = load(`${service}.contract.json`);

    it(`${service}: every ACTION route declares massAction instead of defaulting it`, () => {
      const actions = oracle.routes.filter((route) => route.operation === 'action');
      expect(
        actions.length,
        `${service}.contract.json holds no ACTION routes, so this gate checked nothing (stale or truncated fixture: run pnpm oracle:refresh)`,
      ).toBeGreaterThan(0);

      // Assert the field EXISTS before reading it. A fixture generated by an older
      // oracle has no declared_arguments, which would make the check below vacuously
      // pass for every route - a dropped field must never read as a green gate.
      const fieldless = actions
        .filter((route) => !Array.isArray(route.declared_arguments))
        .map((route) => `${route.method} ${route.uri}`);
      expect(
        fieldless,
        `${service}.contract.json predates declared_arguments, so nothing here is actually checked: run pnpm oracle:refresh`,
      ).toEqual([]);

      const undeclared = actions
        .filter((route) => !(route.declared_arguments ?? []).includes('massAction'))
        .map(
          (route) =>
            `${route.method} ${route.uri}: ACTION with no massAction: at the call site, so its reported mass_action=${route.mass_action} is the constructor default, not a decision`,
        );

      /* eslint-disable-next-line no-console */
      console.log(`${service} bulk-flag declaration: ${actions.length} ACTION routes checked, ${undeclared.length} omit massAction.`);
      expect(undeclared).toEqual([]);
    });
  }
});
