import { describe, it, expect } from 'vitest';
import { readdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, relative, sep } from 'node:path';
import { buildRegistry } from '@gtm/mcp-runtime';
import { linkedinPackages } from '@gtm/mcp-linkedin';
import { idPackages } from '@gtm/mcp-id';
import { orchestrationPackages } from '@gtm/mcp-orchestration';
import { supportPackages } from '@gtm/mcp-support';

// Dash gate, second half.
//
// CLAUDE.md bans the em dash and the en dash as punctuation in "every file and
// every channel". buildRegistry (packages/runtime/src/registry.ts) already
// throws on a tool description, an annotations.title, or any field-level
// .describe() that carries one, which covers every registry tool (the count is
// derived at the bottom of this file, never written down) and, through them,
// the generated public OpenAPI.
//
// This half covers what buildRegistry cannot see, which is the rest of the
// repo: the mount instructions in apps/worker/src/mounts.config.ts (sent to
// every client as server instructions), the three facade meta-tools registered
// by hand in packages/runtime/src/facade.ts, the error prose in
// packages/runtime/src/error-map.ts that the agent reads on every failure, and
// also the shell scripts, the .mjs build tools, the markdown, the config and
// the comments.
//
// It used to scan only packages/ and apps/, only .ts, only string literals, and
// it skipped *.test.ts. Every one of those narrowings was a place a dash could
// sit forever, and twelve of them did: a console.error() in
// bin/build-kb-index.mjs reaches a human exactly like a tool description does,
// and an internal comment is still a file CLAUDE.md covers. So the scan is now
// every line of every text file under this repo root, minus the exclusions
// below, each justified where it is declared. There is no "comments are
// internal prose" carve-out any more.

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const DASH_RE = /[–—]/;

// Directories that are not ours to rewrite, or are regenerated on every build.
//   node_modules  vendored third-party packages
//   dist          tsc / wrangler build output
//   .turbo        turborepo task cache
//   .wrangler     miniflare local dev state (KV blobs, sqlite)
//   coverage      vitest coverage report
//   .git          git internals, including binary packfiles
const SKIP_DIRS = new Set(['node_modules', 'dist', '.turbo', '.wrangler', 'coverage', '.git']);

// The same reasoning at file granularity.
//   pnpm-lock.yaml  generated by pnpm from the package.json set
//   .dev.vars       gitignored local secrets; a test has no business reading it
const SKIP_FILES = new Set(['pnpm-lock.yaml', '.dev.vars']);

// Suffix exclusions.
//   .log            gitignored runtime output (worker.log is a live dispatch
//                   log; a dash in it came from upstream data, not from us)
//   .contract.json  machine-generated dumps of each backend's own contract
//                   surface, written by bin/oracle-refresh.sh. Regenerated
//                   rather than edited, and they carry no authored prose, so a
//                   dash there would be a backend-side fix, not one here.
const SKIP_SUFFIXES = ['.log', '.contract.json'];

// Deliberately NOT excluded, though it is generated:
// packages/mcp.support/kb_articles/kb-index.ts. Its text is served to users
// verbatim by search_knowledge / get_kb_article, so a dash in it is a real
// defect; the fix is in the source article under customer_success/kb/ followed
// by `node bin/build-kb-index.mjs`, not a waiver here. The hand-maintained
// fixtures (ratchet.json, drift-ledger.json, the two allowlists,
// research-parity/baseline.json) are scanned for the same reason: their long
// `_comment` bodies are authored English like any other doc in the tree.

// The only waived LINES. Both DASH_RE character classes have to contain the
// characters in order to match them. The waiver is by exact text, so it stops
// applying the moment either line is edited or copied into a third file. The
// expected text is spelled with \u escapes and compares equal to the literal
// source line at runtime.
const DASH_RE_LINE = 'const DASH_RE = /[\u2013\u2014]/;';
const DASH_RE_FILES = new Set(['packages/runtime/src/registry.ts', 'tests/dash-lint.test.ts']);

const isWaived = (rel: string, line: string): boolean =>
  DASH_RE_FILES.has(rel) && line.trim() === DASH_RE_LINE;

const relPath = (path: string): string => relative(ROOT, path).split(sep).join('/');

function textFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      out.push(...textFiles(path));
    } else if (entry.isFile()) {
      if (SKIP_FILES.has(entry.name)) continue;
      if (SKIP_SUFFIXES.some((suffix) => entry.name.endsWith(suffix))) continue;
      out.push(path);
    }
  }
  return out;
}

/** `rel:line: text` per offending line. Pure, so the probes can hand it a fake file. */
function offendingLines(rel: string, text: string): string[] {
  const hits: string[] = [];
  text.split('\n').forEach((line, i) => {
    if (!DASH_RE.test(line) || isWaived(rel, line)) return;
    hits.push(`${rel}:${i + 1}: ${line.trim().slice(0, 120)}`);
  });
  return hits;
}

const offenders = (path: string): string[] => offendingLines(relPath(path), readFileSync(path, 'utf8'));

describe('no em/en dash anywhere in the tree', () => {
  const files = textFiles(ROOT);
  const scanned = new Set(files.map(relPath));

  // Guards the widening itself: the narrow version of this gate passed every
  // one of these files by never looking at them.
  it('scans the whole tree, not just .ts under packages/ and apps/', () => {
    expect(files.length).toBeGreaterThan(100);
    for (const rel of [
      'bin/schema-weight.mjs',
      'bin/lib/register-ts.mjs',
      'bin/mcp-dev.sh',
      'apps/worker/wrangler.toml',
      'PACKAGES.md',
      'tests/dash-lint.test.ts',
      'packages/mcp.support/kb_articles/mintlify-retriever.ts',
      'fixtures/research-parity/baseline.json',
    ]) {
      expect(scanned.has(rel), `${rel} is no longer scanned by the dash gate`).toBe(true);
    }
  });

  it('finds none', () => {
    const hits = files.flatMap(offenders);
    expect(hits, `banned em/en dash (CLAUDE.md):\n${hits.join('\n')}`).toEqual([]);
  });

  it('flags a comment, a shell line and a markdown line, not just a string literal', () => {
    const dash = '\u2014';
    const probe = [
      `// a comment ${dash} now counts`,
      `echo "shell prose ${dash} counts"`,
      `A markdown sentence ${dash} counts.`,
      'a clean line',
    ].join('\n');
    expect(offendingLines('some/file.ts', probe)).toHaveLength(3);
  });

  it('waives the DASH_RE line only in the two files that define it, and only verbatim', () => {
    expect(offendingLines('packages/runtime/src/registry.ts', DASH_RE_LINE)).toEqual([]);
    expect(offendingLines('tests/dash-lint.test.ts', `  ${DASH_RE_LINE}`)).toEqual([]);
    // The same text in a third file, or edited text in a waived file, still fails.
    expect(offendingLines('packages/shared/contracts.ts', DASH_RE_LINE)).toHaveLength(1);
    expect(
      offendingLines('packages/runtime/src/registry.ts', DASH_RE_LINE.replace('DASH_RE', 'OTHER_RE')),
    ).toHaveLength(1);
  });
});

// The registry half, asserted here so both halves are described in one place
// and so the tool count is READ off the registry instead of being written into
// a comment that then rots (it claimed 232 while the registry served 250).
// buildRegistry throws on a dash in any published tool string.
const REGISTRY = buildRegistry([
  ...linkedinPackages,
  ...idPackages,
  ...orchestrationPackages,
  ...supportPackages,
]);

describe('registry half of the dash gate', () => {
  it(`buildRegistry accepted all ${REGISTRY.byName.size} registry tools`, () => {
    expect(REGISTRY.byName.size).toBeGreaterThan(0);
  });
});
